### ISSUE TITLE
Crash on coin allocation

### ISSUE THREAD

**Issue by darosior** [revault/watchtower_paper#66]
```python
DEBUG:root:Checking if we need feebump Cancel tx for vault 5721. Tx feerate: 79.46753246753246, next block feerate: 97
Traceback (most recent call last):
  File "/home/darosior/projects/revault/watchtower_paper/Model/main.py", line 96, in <module>
    sim.run(start_block, end_block)
  File "/home/darosior/projects/revault/watchtower_paper/Model/simulation.py", line 410, in run
    self.confirm_sequence(block)
  File "/home/darosior/projects/revault/watchtower_paper/Model/simulation.py", line 385, in confirm_sequence
    self.wt.finalize_cancel(tx, height)
  File "/home/darosior/projects/revault/watchtower_paper/Model/statemachine.py", line 1063, in finalize_cancel
    self.maybe_replace_cancel(height, tx)
  File "/home/darosior/projects/revault/watchtower_paper/Model/statemachine.py", line 1093, in maybe_replace_cancel
    vault.allocate_coin(coin)
  File "/home/darosior/projects/revault/watchtower_paper/Model/statemachine.py", line 80, in allocate_coin
    assert coin.id not in self.fb_coins
AssertionError
```

**Comment by JSwambo** [comment]
#67 fixes this
